router bgp 64512
 bgp router-id 10.10.10.1
 no bgp ebgp-requires-policy
 
 ! Create a pool for dynamic neighbors
 neighbor k8s-nodes peer-group
 neighbor k8s-nodes remote-as 64513
 neighbor k8s-nodes soft-reconfiguration inbound
 
 ! Dynamically accept any BGP peer coming from your local subnet
 bgp listen range 10.10.10.0/24 peer-group k8s-nodes
 
 address-family ipv4 unicast
  neighbor k8s-nodes activate
 exit-address-family
