# yaml-language-server: $schema=.schema/talconfig.json

.variables:
  cluster_name: &cname homelab

clusterName: *cname
# https://github.com/siderolabs/talos/releases
talosVersion: v1.13.5 
# https://kubernetes.io/releases/
kubernetesVersion: v1.36.2
endpoint: https://${control_plane_ip}:6443
allowSchedulingOnMasters: true
additionalApiServerCertSans:
  - homelab.local
  - home.pontifex.dev
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  # Will install Cilium CNI
  name: none
nodes:
  - hostname: homelab-control-01
    installDisk: /dev/vda
    ipAddress: ${control_plane_ip}
    controlPlane: true
    certSANs:
      - ${control_plane_ip}
    nodeLabels:
      app.kubernetes.io/cluster: *cname
      topology.kubernetes.io/region: home
      topology.kuberentes.io/zone: home-a

patches:
  # Replace kube-proxy with Cilium
  - |-
    cluster:
      proxy:
        disabled: true
    machine:
      sysctls:
        net.ipv4.ip_forward: "1"
        net.ipv6.conf.all.forwarding: "1"
        net.ipv4.conf.all.rp_filter: "0"
        net.ipv4.conf.default.rp_filter: "0"

